services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: domains_sweden
      MYSQL_DATABASE: domains_sweden
      MYSQL_USER: domains_sweden
      MYSQL_PASSWORD: domains_sweden
    ports:
      - "3306:3306"
  domains-sweden:
    build: .
    container_name: domains-sweden
    environment:
      - PORT=:80
      - BASE_URL=http://localhost:8080
      - COOKIE_SECRET=
      - DATABASE=mysql
      - DATABASE_NAME=domains_sweden
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=domains_sweden
      - DATABASE_PASSWORD=domains_sweden
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
      - SMTP_HOST=
      - SMTP_PORT=
      - SMTP_SENDER=
      - STRICT_TRANSPORT_SECURITY=false
      - REQUESTS_PER_MINUTE=5
      - CACHE_PARAMETER=
      - CACHE_MAX_AGE=
    depends_on:
      - db
    ports:
      - "8080:80"

volumes:
  db_data: {}
